### ISSUE TITLE
centroid is equal to meanfreq

### ISSUE THREAD

**Issue by KostyaEsmukov** [primaryobjects/voice-gender#1]
Hi,

Just a little note: `meanfreq` and `centroid` are calculated the same way, so there is no need to include both of them.
See the `seewave:specprop` implementation: https://github.com/cran/seewave/blob/97501b30e1475710511d4a147d14c17b2d4ca96c/R/seewave.r#L6030

`sum(amp*freq)` is the same as `sum(freq * amp)` for flat lists.

PS Thank you very much for this work. Greatly appreciated.

**Comment by primaryobjects** [comment]
Thank you! I'll leave this in the data-set for now, but I appreciate this note.
