### ISSUE TITLE
object 'summary1' not found

### ISSUE THREAD

**Issue by singhshantanu1996** [primaryobjects/voice-gender#11]
Getting the following error -->
```
Listening on http://127.0.0.1:6745
[1] "Using model: SVM"
[1] "./temp60412"
[1] "temp55759.wav"
[1] "C:/Users/Shan/Desktop/VoiceAnalytics/project/voice-gender-master/Web/temp60412"
   |                                                  | 0 % ~calculating  
Warning: Error in process: object 'summary1' not found
  77: process [C:\Users\Shan\Desktop\VoiceAnalytics\project\voice-gender-master\Web/server.R#412]
  76: processFile [C:\Users\Shan\Desktop\VoiceAnalytics\project\voice-gender-master\Web/server.R#152]
  72: observeEventHandler [C:\Users\Shan\Desktop\VoiceAnalytics\project\voice-gender-master\Web/server.R#70]
   1: runApp
```
 I have already tried installing all the repositories, they all seem to be working nicely. 
Also, I have seen the other issue which was closed, Your answer was about installing the repos properly but I have done that successfully and it is still not working.

**Comment by primaryobjects** [comment]
Please see the fix [here](https://github.com/primaryobjects/voice-gender/blob/heroku/Web/server.R) in the function `process` where `summary1` is initialized. Thanks!
