### ISSUE TITLE
How generate "svm.bin,xgboostLarge.bin,stacked.bin,data.bin,tunedForest.bin,xgboostSmall.bin" from voice.csv?

### ISSUE THREAD

**Issue by zxdposter** [primaryobjects/voice-gender#12]
I want training data from voice.csv, how can I do that?

**Comment by primaryobjects** [comment]
Please see the readme and full [article](http://www.primaryobjects.com/2016/06/22/identifying-the-gender-of-a-voice-using-machine-learning/) for details. Thanks.

**Comment by zxdposter** [comment]
I already see it, but made no mention of how to generate the binary files. @primaryobjects Can give some hints?
