### ISSUE TITLE
WebSocket error when uploading a vocaroo clip

### ISSUE THREAD

**Issue by DoMiNeLa10** [primaryobjects/voice-gender#13]
This application seems to fail when a voice link is given. I've tried Firefox (with and without tracking protection), and Chromium. In latter, I get following error when trying to upload the test clip:
![image](https://user-images.githubusercontent.com/16294095/71216187-21875480-22ba-11ea-81ed-6c72f34ce0fa.png)

**Comment by primaryobjects** [comment]
It may be out of date. Please feel free to let me know if you find a fix. Thank you.
