### ISSUE TITLE
"Threshold"

### ISSUE THREAD

**Issue by LizaNi** [primaryobjects/voice-gender#16]
Hello,

interesting project! I'm using the demo website output and am trying to understand what "Threshold" means in the output table there. Is it like, over a certain percentage is female and below it is male? Or does it have some other meaning?
I could not seem to find a clear answer by reading the article.

**Comment by primaryobjects** [comment]
Hi, the threshold value is not related to the percentage over or under a certain classification. It’s simply a mathematical marker. It could be used for informational purposes, or otherwise ignored. Thanks.
