### ISSUE TITLE
Setup Instructions request

### ISSUE THREAD

**Issue by dbarkelew** [primaryobjects/voice-gender#18]
Can install instructions be provided?

Been trying to run this locally, got all the dependent packages installed but now running into this error when I try to analyze a small wav file that does work on the demo site. "Warning: Error in process: object 'summary1' not found"

**Comment by primaryobjects** [comment]
[Documentation](https://github.com/primaryobjects/voice-gender#voice-gender) regarding the data-set is available in the repo.

The error regarding `summary1` is likely related to running the web-based version. Please feel free to share any setup instructions that you use and feel free to create a fork or pull request. Thank you!
