### ISSUE TITLE
Raw WAV files repository

### ISSUE THREAD

**Issue by NullInfinity** [primaryobjects/voice-gender#2]
In the README it says the raw WAV files used to generate the csv file are available in another repository, but there was no link. Where are the WAV files available?

**Comment by primaryobjects** [comment]
I think the best I can do, is to point to the links in the references of the [dataset](https://www.kaggle.com/primaryobjects/voicegender).

You can also build your own features from wav files by using the [warbleR](https://cran.r-project.org/web/packages/warbleR/warbleR.pdf) package, which is an open-source package in R (linux-compatible), for doing the audio analysis. The method "specan" gives 22 acoustic features.
