### ISSUE TITLE
Error on the demo website

### ISSUE THREAD

**Issue by obrassard** [primaryobjects/voice-gender#20]
Hello ! I just wanted to let you know that there seems to be a problem with the demo site of this project, since no matter which audio file or Vocaroo link is used, an error is displayed like that : 
<img width="685" alt="Capture d’écran, le 2023-01-12 à 11 44 16" src="https://user-images.githubusercontent.com/17227551/212128558-45f7c202-3caf-4512-a7ca-e2cdc6410df1.png">

**Comment by primaryobjects** [comment]
The site should be working again. Please note, due to Heroku discontinuing free hosting for applications, the app may not be able to stay online without assistance. Thank you.

**Comment by obrassard** [comment]
Thank you !

**Comment by Poopooracoocoo** [comment]
> The site should be working again. Please note, due to Heroku discontinuing free hosting for applications, the app may not be able to stay online without assistance. Thank you.

Is it at all possible to migrate off it and use GitHub Pages or something? 🙏
