### ISSUE TITLE
[Request] Publish hvoice-primaryobjects.rhcloud.com to a repo

### ISSUE THREAD

**Issue by gerbill** [primaryobjects/voice-gender#4]
Hello, Kory!
Absolutely fascinated by your voice-gender recognition software. 
Tested it at http://voice-primaryobjects.rhcloud.com and I'm amazed how good is it at recognizing gender. I had no idea any software could be that good at it.

I was wondering if it is possible for you to publish source codes for the entire web service at http://voice-primaryobjects.rhcloud.com so I could set it up and translate it in order to make it available for Russian-speaking audience.

Thanks again for the wonderful work you've done!

**Comment by primaryobjects** [comment]
Thank you for the kind comments! :)
