### ISSUE TITLE
When upload .wav file, occurs error

### ISSUE THREAD

**Issue by googgkstmdwo** [primaryobjects/voice-gender#5]
[1] "C:/Users/googg/Desktop/Git/voice-gender/Web/temp47684"
   |                                                  | 0 % ~calculating  
Warning: Error in process: object 'summary1' not found
Stack trace (innermost first):
    70: process [C:\Users\googg\Desktop\Git\voice-gender\Web/server.R#412]
    69: processFile [C:\Users\googg\Desktop\Git\voice-gender\Web/server.R#152]
    68: eval [C:\Users\googg\Desktop\Git\voice-gender\Web/server.R#71]
    67: eval
    66: withProgress
    65: observeEventHandler [C:\Users\googg\Desktop\Git\voice-gender\Web/server.R#70]
     1: runApp

thank you.

**Comment by primaryobjects** [comment]
Please check that you have all dependencies installed. You may also want to try the client version instead of the web for troubleshooting. Thanks.
