### ISSUE TITLE
Add a license 

### ISSUE THREAD

**Issue by xuezhma** [primaryobjects/voice-gender#7]
Hello, thx for the awesome project. Could you please add a license to this repo so I can use it in my project?

**Comment by primaryobjects** [comment]
Please see the readme for the [copyright](https://github.com/primaryobjects/voice-gender/blob/master/readme.md#copyright). Thanks.

**Comment by hunternet93** [comment]
Hi @primaryobjects, so by this do you mean you do not allow others to redistribute, modify, or include this project in derivative works?
