### ISSUE TITLE
different mean frequency from the code and the website

### ISSUE THREAD

**Issue by fzhang612** [primaryobjects/voice-gender#8]
First, thanks for the great work, very helpful!

I cloned this repo the other day and tried it on my own wave data. One thing I noticed is that the features calculated by `specan3()` in file sound.R are different from what I get by uploading the same file to https://voicegender.herokuapp.com/. For example for one 10s wave file, I got mean frequency of 165hz by running `specan3()` and 106hz from your website.

 Is it possible that you use different pre-process on your website? If necessary I can provide the 10s wav file.

Thanks!

**Comment by primaryobjects** [comment]
The web application uses the same `specan3` function, but also uses a combination of models to return a final prediction. That could account for the difference that you're seeing.
