### ISSUE TITLE
Question about IQR

### ISSUE THREAD

**Issue by gcr** [primaryobjects/voice-gender#9]
Hello Kory! I have a question about the final (100%) gender classification model:

The figure on your post shows that CART thinks a voice is male if the band-limited fundamental frequency is less than 140 hz and the band-limited IQR is **greater** than 70hz and female otherwise. However, shouldn't the IQR be **less than** 70 hz for male voices?

I'm not quite sure what IQR **means**. My intuition says IQR seems related to the variance of the frequency, so if the voice intonation varies quite a lot, it should have a high IQR and if the voice is monotone it should have a low IQR. Does that sound right to you?

**Comment by primaryobjects** [comment]
The CART model generates its values based upon the feature data and from associations that it sees within the data. In this case, IQR was found to be significant. You may want to check out the [Kaggle](https://www.kaggle.com/primaryobjects/voicegender) thread for more details. Thanks.
